In [1]:
import numpy as np

In [2]:
pwd

'C:\\Python Files\\AluminaConcEstimator\\NoteBooks'

In [3]:
import sys
sys.path.append('../')

In [4]:
from Refactor.Model import VariableVector

In [5]:
# Create a State Vector Variables
States = VariableVector(cAl2O3=3.5, deltag=0, ACD= 2.93, deltaI=0)

In [6]:
# View the vector
States.vector

array([[3.5 ],
       [0.  ],
       [2.93],
       [0.  ]])

In [7]:
# View its dictionary/definition
States.dictionary

{'cAl2O3': 0, 'deltag': 1, 'ACD': 2, 'deltaI': 3}

In [8]:
# View a variable using the dictionary
States.variable('ACD')

2.93

In [9]:
# edit a single variable in the vector
States.setvariable('cAl2O3', 3.03)
States.variable('cAl2O3')

3.03

In [10]:
from Refactor.Model import ControlMatrix

In [11]:
CM = ControlMatrix(4,3,1)
CM.array(1)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
CM._array

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [13]:
CM.setarray(0, np.ones((4,3)))

True

In [14]:
CM.setarray(1, np.ones((4,3))*2)

True

In [15]:
CM.array(1)

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [16]:
CM.setarray(1, np.ones((3,4)))

Wrong Shape


False

In [17]:
CM.setarray(2, np.ones((4,3)))

Wrong Order


False

In [18]:
np.shape(CM._array)[0]

2