In [2]:
import numpy as np

In [5]:
statevars = {'cAl2O3' : 3.5, 'deltag' : 0.0, 'ACD': 2.97, 'deltaI': 100.0}
statevars

{'cAl2O3': 3.5, 'deltag': 0.0, 'ACD': 2.97, 'deltaI': 100.0}

In [6]:
x = np.array([[statevars['cAl2O3']], [statevars['deltag']], [statevars['ACD']], [statevars['deltaI']]])
x

array([[  3.5 ],
       [  0.  ],
       [  2.97],
       [100.  ]])

In [7]:
stateindex = {'cAl2O3' : 0, 'deltag' : 1, 'ACD': 2, 'deltaI': 3}
stateindex

{'cAl2O3': 0, 'deltag': 1, 'ACD': 2, 'deltaI': 3}

In [8]:
x[stateindex['cAl2O3']]

array([3.5])

In [9]:
np.asscalar(x[stateindex['cAl2O3']])

<ipython-input-9-67853547430b>:1: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  np.asscalar(x[stateindex['cAl2O3']])


3.5

In [10]:
x.item(stateindex['cAl2O3'])

3.5

In [3]:
def A(dt, const, dtlinear):
    return const + dtlinear*dt

In [12]:
Am =A(5, np.array([[1, 2], [3, 4]]), np.array([[0, 0], [0, 1]]))

In [13]:
np.shape(Am)

(2, 2)

In [15]:
def deltat(carray, dt=0, dtarray=0):
    if (dt==0) or (dtarray.any() is False):
        return carray
    else:
        return carray + dtarray*dt

In [5]:
deltat(np.array([[1, 2], [3, 4]]))

array([[1, 2],
       [3, 4]])

In [6]:
deltat(np.array([[1, 2], [3, 4]]), 0)

array([[1, 2],
       [3, 4]])

In [7]:
deltat(np.array([[1, 2], [3, 4]]), 5, np.array([[0, 0], [0, 1]]))

array([[1, 2],
       [3, 9]])

In [8]:
A1 = np.array([[1, 2], [3, 4]])
A1

array([[1, 2],
       [3, 4]])

In [19]:
DT = 0
D1 = np.array([[0, 0], [0, 1]])
D1

array([[0, 0],
       [0, 1]])

In [20]:
deltat(A1, DT, D1)

array([[1, 2],
       [3, 4]])

In [67]:
def createvector(**keywords):
    vectordict = {}
    vector = np.array([])
    index = -1
    for key in keywords:
        index +=1
        vectordict[key] = index
        appended = np.array([keywords[key]])
        if index == 0:
            vector = appended
        else:
            vector = np.vstack([vector, appended])
    return vectordict, vector
    

In [68]:
createvector(cAl2O3= 3.5, deltag = 0.1, ACD = 2.93, deltaI=100.0)

({'cAl2O3': 0, 'deltag': 1, 'ACD': 2, 'deltaI': 3},
 array([[  3.5 ],
        [  0.1 ],
        [  2.93],
        [100.  ]]))

In [70]:
statelookup, statevector = createvector(cAl2O3= 3.5, deltag = 0.1, ACD = 2.93, deltaI=100.0)

In [71]:
inputlookup, inputvector = createvector(g0 = 0.0, b0= 0.0, I0 = 126000.0)

In [72]:
statelookup

{'cAl2O3': 0, 'deltag': 1, 'ACD': 2, 'deltaI': 3}

In [73]:
inputlookup

{'g0': 0, 'b0': 1, 'I0': 2}

In [74]:
statevector

array([[  3.5 ],
       [  0.1 ],
       [  2.93],
       [100.  ]])

In [77]:
statevector[statelookup['cAl2O3']].item()

3.5

In [78]:
inputvector

array([[     0.],
       [     0.],
       [126000.]])

In [80]:
inputvector[inputlookup['I0']].item()

126000.0

In [29]:
a = np.zeros((3, 4, 4), float)
a

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [32]:
a[0] = 1.3
a[1] = np.arange(16).reshape(4,4)
a[2] = np.arange(16).reshape(4,4)/(-10)
a

array([[[ 1.3,  1.3,  1.3,  1.3],
        [ 1.3,  1.3,  1.3,  1.3],
        [ 1.3,  1.3,  1.3,  1.3],
        [ 1.3,  1.3,  1.3,  1.3]],

       [[ 0. ,  1. ,  2. ,  3. ],
        [ 4. ,  5. ,  6. ,  7. ],
        [ 8. ,  9. , 10. , 11. ],
        [12. , 13. , 14. , 15. ]],

       [[-0. , -0.1, -0.2, -0.3],
        [-0.4, -0.5, -0.6, -0.7],
        [-0.8, -0.9, -1. , -1.1],
        [-1.2, -1.3, -1.4, -1.5]]])

In [33]:
dims = np.shape(a)
dims

(3, 4, 4)

In [34]:
A = np.zeros_like(a[0], dtype=float)
dt = 2
for index in range(dims[0]):
    A = A + a[index]*(dt**index)
    print(A)
A

[[1.3 1.3 1.3 1.3]
 [1.3 1.3 1.3 1.3]
 [1.3 1.3 1.3 1.3]
 [1.3 1.3 1.3 1.3]]
[[ 1.3  3.3  5.3  7.3]
 [ 9.3 11.3 13.3 15.3]
 [17.3 19.3 21.3 23.3]
 [25.3 27.3 29.3 31.3]]
[[ 1.3  2.9  4.5  6.1]
 [ 7.7  9.3 10.9 12.5]
 [14.1 15.7 17.3 18.9]
 [20.5 22.1 23.7 25.3]]


array([[ 1.3,  2.9,  4.5,  6.1],
       [ 7.7,  9.3, 10.9, 12.5],
       [14.1, 15.7, 17.3, 18.9],
       [20.5, 22.1, 23.7, 25.3]])